// ═══════════════════════════════════════════════════════════════════
//  PLUDINI — Données · Espèces réelles de Lettonie / Vidzeme
// ═══════════════════════════════════════════════════════════════════

export const RARITY = {
  commun:      { l:'Commun',      p:5,   c:'#8B9B6E' },
  peu_commun:  { l:'Peu commun',  p:15,  c:'#C08A3E' },
  rare:        { l:'Rare',        p:40,  c:'#B5602F' },
  tres_rare:   { l:'Très rare',   p:100, c:'#8B3A2E' },
}

export const SIZE_MULT = { xs:1, s:1.5, m:2, l:2.5, xl:3 }

// multiplicateur de points selon la taille du poisson pêché (remplace la
// qualité de photo pour cette catégorie — trois paliers par espèce, définis
// via son champ tailleCm)
export const FISH_SIZE_MULT = { petit:1, moyen:1.6, grand:2.5 }

export const METHODS = {
  eye:   { l:'Vue directe',     mult:3,   c:'#4A5D32', on:'#EDE7D8' },
  scope: { l:'Longue-vue',      mult:2.5, c:'#6B7F4E', on:'#EDE7D8' },
  night: { l:'Vision nocturne', mult:2,   c:'#93A576', on:'#2B2620' },
  cam:   { l:'Caméra piège',    mult:1,   c:'#C3CDAE', on:'#3B4429' },
}

export const PLAYERS = [
  { id:'G', name:'Gaël' },
  { id:'P', name:'Pierre' },
  { id:'E', name:'Elena' },
  { id:'F', name:'Ferdinand' },
]

export const CATS = [
  { id:'mammiferes', e:'🦁', n:'Mammifères', lat:'Mammalia', subs:[
      { id:'Cervidés', lat:'Cervidae' }, { id:'Canidés', lat:'Canidae' },
      { id:'Félidés', lat:'Felidae' }, { id:'Mustélidés', lat:'Mustelidae' },
      { id:'Rongeurs', lat:'Rodentia / Lagomorpha' }, { id:'Autres', lat:'Erinaceidae / Suidae' },
  ]},
  { id:'oiseaux', e:'🦅', n:'Oiseaux', lat:'Aves', subs:[
      { id:'Gruidés', lat:'Gruidae' }, { id:'Strigidés', lat:'Strigidae' },
      { id:'Picidés', lat:'Picidae' }, { id:'Accipitridés', lat:'Accipitridae' },
      { id:'Ciconiidés', lat:'Ciconiidae' }, { id:'Corvidés', lat:'Corvidae' },
      { id:'Tétraonidés', lat:'Tetraonidae' }, { id:'Paridés', lat:'Paridae' },
      { id:'Muscicapidés', lat:'Muscicapidae' }, { id:'Alcédinidés', lat:'Alcedinidae' },
      { id:'Anatidés', lat:'Anatidae' }, { id:'Fringillidés', lat:'Fringillidae' },
  ]},
  { id:'arbres', e:'🌳', n:'Arbres', lat:'Arbores', subs:[
      { id:'Fagacées', lat:'Fagaceae' }, { id:'Bétulacées', lat:'Betulaceae' },
      { id:'Pinacées', lat:'Pinaceae' }, { id:'Salicacées', lat:'Salicaceae' },
      { id:'Rosacées', lat:'Rosaceae' }, { id:'Sapindacées', lat:'Sapindaceae' },
      { id:'Malvacées', lat:'Malvaceae' },
  ]},
  { id:'arbustes', e:'🌿', n:'Arbustes', lat:'Frutices', subs:[
      { id:'Éléagnacées', lat:'Elaeagnaceae' }, { id:'Éricacées', lat:'Ericaceae' },
      { id:'Bétulacées', lat:'Betulaceae' }, { id:'Rosacées', lat:'Rosaceae' },
      { id:'Adoxacées', lat:'Adoxaceae' }, { id:'Cupressacées', lat:'Cupressaceae' },
  ]},
  { id:'champignons', e:'🍄', n:'Champignons', lat:'Fungi', subs:[
      { id:'Bolétales', lat:'Boletales' }, { id:'Agaricales', lat:'Agaricales' },
      { id:'Russulales', lat:'Russulales' }, { id:'Cantharellales', lat:'Cantharellales' },
  ]},
  { id:'lichens', e:'🍃', n:'Lichens & mousses', lat:'Lichenes / Bryophyta', subs:[
      { id:'Lichens', lat:'Lichenes' }, { id:'Mousses', lat:'Bryophyta' },
  ]},
  { id:'humains', e:'🧍', n:'Humains', lat:'Homo sapiens', subs:[
      { id:'Résidents', lat:'Hominidae · permanents' },
      { id:'Travailleurs', lat:'Hominidae · sur place' },
      { id:'Visiteurs', lat:'Hominidae · saisonniers' },
  ]},
  { id:'domestiques', e:'🐾', n:'Animaux domestiques', lat:'Animalia domestica', subs:[
      { id:'Chiens', lat:'Canis lupus familiaris' },
      { id:'Chats', lat:'Felis catus' },
  ]},
  { id:'insectes', e:'🦋', n:'Insectes', lat:'Insecta', subs:[
      { id:'Lépidoptères', lat:'Lepidoptera' }, { id:'Coléoptères', lat:'Coleoptera' },
      { id:'Odonates', lat:'Odonata' }, { id:'Hyménoptères', lat:'Hymenoptera' },
  ]},
  { id:'poissons', e:'🐟', n:'Poissons', lat:'Pisces', subs:[
      { id:'Esocidés', lat:'Esocidae' }, { id:'Percidés', lat:'Percidae' }, { id:'Cyprinidés', lat:'Cyprinidae' },
  ]},
]

export const SPECIES = [
  { id:'elan', n:'Élan', lat:'Alces alces', e:'🫎', cat:'mammiferes', sub:'Cervidés', r:'rare', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    anecdote:"L'élan est le plus grand cervidé du monde : un mâle adulte peut atteindre 800 kg. Il nage remarquablement bien et peut plonger jusqu'à 5 m pour atteindre des plantes aquatiques. Ses longues pattes lui permettent de traverser 1 m de neige sans effort.",
    saisons:{printemps:'Mise bas en mai-juin. Les femelles deviennent très défensives.',ete:'Fréquente les zones humides pour se nourrir et échapper aux insectes.',automne:'Rut en septembre-octobre. Les mâles deviennent imprévisibles.',hiver:'Se rabat sur les jeunes pousses de saule et bouleau. Perd ses bois.'},
    alim:'Saule, bouleau, plantes aquatiques. 20–30 kg/jour.',
    hab:'Zones humides, lisières. Territoire 10–30 km². Solitaire.',
    dng:'Femelle avec veau dangereuse. Mâle imprévisible en rut (sept–oct).' },
  { id:'cerf', n:'Cerf élaphe', lat:'Cervus elaphus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le brame du cerf porte à plus de 5 km par nuit calme. Les bois repoussent chaque année à raison de 2 cm par jour — c'est le tissu à croissance la plus rapide du règne animal.",
    saisons:{printemps:'Chute des bois puis repousse sous velours. Naissance des faons en mai-juin.',ete:'Pelage roux vif. Vie en hardes séparées mâles/femelles.',automne:'Le brame. Les mâles rassemblent leurs harems et combattent.',hiver:'Pelage gris épais. Regroupements pour économiser l\'énergie.'},
    alim:'Herbes, baies, glands, champignons, écorce.',
    hab:'Forêt et lisières. Sociable en hardes.', dng:'Aucun danger hors rut.' },
  { id:'chevreuil', n:'Chevreuil', lat:'Capreolus capreolus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le chevreuil est le seul ongulé à pratiquer la diapause embryonnaire : fécondé en juillet, l'embryon ne s'implante qu'en décembre. L'aboiement qu'on entend en forêt, c'est lui — un cri d'alarme sec qui prévient tout le voisinage.",
    saisons:{printemps:'Naissance des faons en mai. Bois débarrassés du velours.',ete:'Rut en juillet-août. Poursuites en cercles caractéristiques.',automne:'Pelage gris-brun. Constitution des réserves.',hiver:'Regroupement en petites hardes. Chute des bois en octobre-novembre.'},
    alim:'Pousses, baies, champignons, lierre. Sélectif.',
    hab:'Lisières et clairières. Territoire 30–60 ha.', dng:'Aucun.' },
  { id:'sanglier', n:'Sanglier', lat:'Sus scrofa', e:'🐗', cat:'mammiferes', sub:'Autres', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Racines, glands, vers, larves, charognes. Omnivore.',
    hab:'Forêt dense, souilles près de l\'eau. En compagnies.',
    dng:'Laie avec marcassins agressive. Peut charger.' },
  { id:'renard', n:'Renard roux', lat:'Vulpes vulpes', e:'🦊', cat:'mammiferes', sub:'Canidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le renard utilise le champ magnétique terrestre pour chasser : il oriente son bond nord-est et réussit 73 % de ses attaques dans cet axe, contre 18 % dans les autres directions. Il possède plus de 20 vocalisations différentes.",
    saisons:{printemps:'Naissance des renardeaux en avril. Les adultes chassent en permanence.',ete:'Émancipation progressive des jeunes. Régime riche en fruits et insectes.',automne:'Dispersion des jeunes. Constitution des réserves de graisse.',hiver:'Rut en janvier-février. Cris nocturnes caractéristiques.'},
    alim:'Rongeurs, lapins, oeufs, fruits, insectes.',
    hab:'Lisières, bocage. Terrier actif sur la propriété.',
    dng:'La gale sarcoptique est contagieuse pour le chien — surveiller si un individu semble dégarni.' },
  { id:'loup', n:'Loup gris', lat:'Canis lupus', e:'🐺', cat:'mammiferes', sub:'Canidés', r:'tres_rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Cerf, chevreuil, sanglier, castor. Chasse en meute.',
    hab:'Grands massifs forestiers. Territoire 100–300 km².',
    dng:'Très craintif envers l\'humain. Surveille les chiens.' },
  { id:'viverrin', n:'Chien viverrin', lat:'Nyctereutes procyonoides', e:'🦝', cat:'mammiferes', sub:'Canidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Grenouilles, poissons, baies, rongeurs, charognes.',
    hab:'Zones humides. Espèce invasive. Torpeur hivernale.',
    dng:'⚠️ Vecteur de rage. Danger pour la basse-cour.' },
  { id:'lynx', n:'Lynx boréal', lat:'Lynx lynx', e:'🐆', cat:'mammiferes', sub:'Félidés', r:'tres_rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le lynx ne rugit pas : il miaule, ronronne et pousse des cris rauques. En Lettonie, la population est passée de moins de 100 individus dans les années 1950 à environ 1 200 aujourd'hui. Il peut bondir sur 7 mètres d'un seul élan.",
    saisons:{printemps:'Mise bas en mai. La femelle reste cantonnée près de la tanière.',ete:'Élevage des jeunes. Chasse plus fréquente pour nourrir la portée.',automne:'Les jeunes accompagnent la mère. Territoire parcouru intensément.',hiver:'Rut en février-mars. Traces bien visibles dans la neige.'},
    alim:'Chevreuil (70–80%), cerf, lièvre. Affût et bond.',
    hab:'Forêt dense. Territoire 200–500 km². Solitaire.',
    dng:'Aucun pour l\'humain. Très craintif.' },
  { id:'chat_sauvage', n:'Chat sauvage', lat:'Felis silvestris', e:'🐈', cat:'mammiferes', sub:'Félidés', r:'rare', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Rongeurs, oiseaux, lapereaux.',
    hab:'Forêt de feuillus, lisières broussailleuses. Discret.', dng:'Aucun. Fuit l\'humain.' },
  { id:'blaireau', n:'Blaireau européen', lat:'Meles meles', e:'🦡', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Vers de terre (80%), baies, insectes, rongeurs.',
    hab:'Blairaudière multigénérationnelle. Torpeur hivernale.', dng:'Inoffensif.' },
  { id:'martre', n:'Martre des pins', lat:'Martes martes', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Rongeurs, oiseaux, oeufs, baies, miel.',
    hab:'Forêt de conifères et mixte. Arboricole.', dng:'Aucun pour l\'humain.' },
  { id:'putois', n:'Putois d\'Europe', lat:'Mustela putorius', e:'🦨', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, rongeurs, oiseaux.',
    hab:'Zones humides, lisières, granges.', dng:'Aucun.' },
  { id:'hermine', n:'Hermine', lat:'Mustela erminea', e:'🐁', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, lapereaux.',
    hab:'Lisières, murets, prairies. Blanche en hiver.', dng:'Aucun.' },
  { id:'loutre', n:'Loutre d\'Europe', lat:'Lutra lutra', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, écrevisses.',
    hab:'Rivière Līčupe, berges des lacs. Marque avec épreintes.', dng:'Aucun.' },
  { id:'vison', n:'Vison d\'Europe', lat:'Mustela lutreola', e:'🦫', cat:'mammiferes', sub:'Mustélidés', r:'tres_rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, poissons, petits rongeurs.',
    hab:'Berges des cours d\'eau. Très menacé en Europe.', dng:'Aucun.' },
  { id:'castor', n:'Castor d\'Eurasie', lat:'Castor fiber', e:'🦫', cat:'mammiferes', sub:'Rongeurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce, rameaux, plantes aquatiques.',
    hab:'Līčupe et lacs. Construit huttes et barrages.', dng:'Aucun.' },
  { id:'ecureuil', n:'Écureuil roux', lat:'Sciurus vulgaris', e:'🐿️', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de conifères, noisettes, glands, champignons.',
    hab:'Forêt de conifères et mixte. Arboricole diurne.', dng:'Aucun.' },
  { id:'lievre', n:'Lièvre d\'Europe', lat:'Lepus europaeus', e:'🐇', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Herbes, écorces, cultures.',
    hab:'Champs, lisières, prairies. Gîte à découvert.', dng:'Aucun.' },
  { id:'herisson', n:'Hérisson', lat:'Erinaceus europaeus', e:'🦔', cat:'mammiferes', sub:'Autres', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, limaces, oeufs.',
    hab:'Jardins, lisières, haies. Nocturne. Hiberne.', dng:'Aucun.' },

  { id:'grue', n:'Grue cendrée', lat:'Grus grus', e:'🪽', cat:'oiseaux', sub:'Gruidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Grains, insectes, vers, amphibiens.',
    hab:'Zones humides. Migratrice. Parade nuptiale spectaculaire.', dng:'Aucun.' },
  { id:'hulotte', n:'Chouette hulotte', lat:'Strix aluco', e:'🦉', cat:'oiseaux', sub:'Strigidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, oiseaux, amphibiens.',
    hab:'Forêt mixte, vieux arbres à cavités. Nocturne.', dng:'Aucun.' },
  { id:'pic_noir', n:'Pic noir', lat:'Dryocopus martius', e:'🐦‍⬛', cat:'oiseaux', sub:'Picidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Fourmis, larves xylophages sous l\'écorce.',
    hab:'Vieilles forêts de conifères. Plus grand pic d\'Europe.', dng:'Aucun.' },
  { id:'pygargue', n:'Pygargue à queue blanche', lat:'Haliaeetus albicilla', e:'🦅', cat:'oiseaux', sub:'Accipitridés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, oiseaux d\'eau, charognes.',
    hab:'Grands lacs, envergure jusqu\'à 2,4m.', dng:'Aucun.' },
  { id:'cigogne_noire', n:'Cigogne noire', lat:'Ciconia nigra', e:'🐦', cat:'oiseaux', sub:'Ciconiidés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, insectes aquatiques.',
    hab:'Forêts humides isolées. Très discrète, farouche.', dng:'Aucun.' },
  { id:'geai', n:'Geai des chênes', lat:'Garrulus glandarius', e:'🐦', cat:'oiseaux', sub:'Corvidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands, faines, insectes, oeufs.',
    hab:'Forêts de feuillus. Sentinelle bruyante de la forêt.', dng:'Aucun.' },
  { id:'grand_tetras', n:'Grand tétras', lat:'Tetrao urogallus', e:'🦃', cat:'oiseaux', sub:'Tétraonidés', r:'tres_rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles de pin, baies, bourgeons.',
    hab:'Vieilles pinèdes. Parade au chant.', dng:'Mâle en parade peut charger.' },
  { id:'mesange', n:'Mésange charbonnière', lat:'Parus major', e:'🐦', cat:'oiseaux', sub:'Paridés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, graines, chenilles.',
    hab:'Jardins, lisières, mangeoires en hiver.', dng:'Aucun.' },
  { id:'rougegorge', n:'Rougegorge familier', lat:'Erithacus rubecula', e:'🐦', cat:'oiseaux', sub:'Muscicapidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, baies.',
    hab:'Sous-bois, haies. Chant matinal caractéristique.', dng:'Aucun.' },
  { id:'buse', n:'Buse variable', lat:'Buteo buteo', e:'🦅', cat:'oiseaux', sub:'Accipitridés', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, rongeurs, charognes.',
    hab:'Lisières, poteaux, vol en cercles au-dessus des champs.', dng:'Aucun.' },
  { id:'martin_pecheur', n:'Martin-pêcheur d\'Europe', lat:'Alcedo atthis', e:'🐦', cat:'oiseaux', sub:'Alcédinidés', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Petits poissons, pêchés en piqué.',
    hab:'Berges de la Līčupe et des lacs. Plumage bleu vif.', dng:'Aucun.' },
  { id:'cygne', n:'Cygne tuberculé', lat:'Cygnus olor', e:'🦢', cat:'oiseaux', sub:'Anatidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Plantes aquatiques, algues.',
    hab:'Grands lacs du territoire. Couples fidèles à vie.', dng:'Peut charger près du nid.' },
  { id:'pinson', n:'Pinson des arbres', lat:'Fringilla coelebs', e:'🐦', cat:'oiseaux', sub:'Fringillidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines, insectes en période de nidification.',
    hab:'Forêts, lisières, jardins. Chant vif et répétitif.', dng:'Aucun.' },

  { id:'chene', n:'Chêne pédonculé', lat:'Quercus robur', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands = nourriture clé pour sanglier, geai, écureuil.',
    hab:'Forêts de feuillus, sols riches. Peut vivre 500+ ans.', dng:'—' },
  { id:'hetre', n:'Hêtre commun', lat:'Fagus sylvatica', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Faines consommées par de nombreux animaux.',
    hab:'Forêts denses, sols frais. Écorce lisse grise.', dng:'—' },
  { id:'bouleau', n:'Bouleau pubescent', lat:'Betula pubescens', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce et rameaux broutés par l\'élan.',
    hab:'Pionnier, zones humides. Écorce blanche typique.', dng:'—' },
  { id:'aulne', n:'Aulne glutineux', lat:'Alnus glutinosa', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines pour tarins et sizerins.',
    hab:'Berges de la Līčupe, sols gorgés d\'eau.', dng:'—' },
  { id:'epicea', n:'Épicéa commun', lat:'Picea abies', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de cônes pour écureuil, bec-croisé.',
    hab:'Dominant de la forêt boréale. Abri du lynx.', dng:'—' },
  { id:'pin', n:'Pin sylvestre', lat:'Pinus sylvestris', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles = nourriture du grand tétras.',
    hab:'Sols pauvres et sableux. Écorce orangée en haut.', dng:'—' },
  { id:'tremble', n:'Tremble', lat:'Populus tremula', e:'🌳', cat:'arbres', sub:'Salicacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce très appréciée du castor et du lièvre.',
    hab:'Pionnier, lisières. Feuilles qui tremblent au vent.', dng:'—' },
  { id:'sorbier', n:'Sorbier des oiseleurs', lat:'Sorbus aucuparia', e:'🌳', cat:'arbres', sub:'Rosacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies rouges pour grives, merles, renard.',
    hab:'Lisières, clairières. Baies orangées en automne.', dng:'—' },
  { id:'tilleul', n:'Tilleul à petites feuilles', lat:'Tilia cordata', e:'🌳', cat:'arbres', sub:'Malvacées', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Fleurs mellifères pour abeilles et bourdons.',
    hab:'Forêts de feuillus, parcs. Arbre symbolique balte.', dng:'—' },
  { id:'erable', n:'Érable plane', lat:'Acer platanoides', e:'🍁', cat:'arbres', sub:'Sapindacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Samares pour rongeurs et oiseaux.',
    hab:'Forêts mixtes. Feuillage jaune-rouge éclatant en automne.', dng:'—' },

  { id:'argousier', n:'Argousier faux-nerprun', lat:'Hippophae rhamnoides', e:'🧡', cat:'arbustes', sub:'Éléagnacées', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies acidulées riches en vitamine C, récoltées à l\'automne.',
    hab:'Sols sableux, bords de rivière. Planté sur la propriété.', dng:'—' },
  { id:'myrtille', n:'Myrtille commune', lat:'Vaccinium myrtillus', e:'🫐', cat:'arbustes', sub:'Éricacées', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies bleu-noir très recherchées, cueillette d\'été.',
    hab:'Sous-bois acides, pinèdes claires.', dng:'—' },
  { id:'noisetier', n:'Noisetier commun', lat:'Corylus avellana', e:'🌰', cat:'arbustes', sub:'Bétulacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Noisettes pour écureuil, geai, loir.',
    hab:'Lisières, sous-bois clairs. Chatons dès février.', dng:'—' },
  { id:'eglantier', n:'Églantier', lat:'Rosa canina', e:'🌹', cat:'arbustes', sub:'Rosacées', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Cynorrhodons riches en vitamine C pour les oiseaux.',
    hab:'Haies, lisières, friches. Fleurs roses en juin.', dng:'⚠️ Tiges épineuses.' },
  { id:'sureau', n:'Sureau noir', lat:'Sambucus nigra', e:'🍇', cat:'arbustes', sub:'Adoxacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies noires pour merles et grives. Fleurs en ombelles blanches.',
    hab:'Haies, lisières, friches humides.', dng:'⚠️ Baies crues légèrement toxiques — à cuire.' },
  { id:'genevrier', n:'Genévrier commun', lat:'Juniperus communis', e:'🌲', cat:'arbustes', sub:'Cupressacées', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies (cônes) pour grives et sittelles.',
    hab:'Landes, pinèdes claires, sols pauvres.', dng:'—' },

  { id:'cepe', n:'Cèpe de Bordeaux', lat:'Boletus edulis', e:'🍄', cat:'champignons', sub:'Bolétales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Symbiose mycorhizienne avec épicéas et pins.',
    hab:'Sous conifères et feuillus. Comestible réputé.', dng:'—' },
  { id:'bolet_orange', n:'Bolet orangé', lat:'Leccinum aurantiacum', e:'🍄', cat:'champignons', sub:'Bolétales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec trembles et bouleaux.',
    hab:'Sous trembles. Chapeau orange vif. Comestible.', dng:'—' },
  { id:'girolle', n:'Girolle', lat:'Cantharellus cibarius', e:'🍄', cat:'champignons', sub:'Cantharellales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec de nombreux arbres.',
    hab:'Forêts moussues. Jaune d\'or, odeur d\'abricot. Comestible.', dng:'—' },
  { id:'amanite', n:'Amanite tue-mouches', lat:'Amanita muscaria', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec bouleaux et épicéas.',
    hab:'Sous bouleaux. Rouge à points blancs.', dng:'⚠️ Toxique — ne pas consommer.' },
  { id:'russule', n:'Russule charbonnière', lat:'Russula cyanoxantha', e:'🍄', cat:'champignons', sub:'Russulales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhizienne.',
    hab:'Forêts de feuillus. Chapeau violacé-vert. Comestible.', dng:'—' },
  { id:'coprin', n:'Coprin chevelu', lat:'Coprinus comatus', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Saprophyte (décompose la matière organique).',
    hab:'Prairies, bords de chemins. Se liquéfie en vieillissant.', dng:'—' },

  { id:'cladonie', n:'Cladonie des rennes', lat:'Cladonia rangiferina', e:'🍃', cat:'lichens', sub:'Lichens', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nourriture hivernale des rennes (nord).',
    hab:'Sols pauvres, pinèdes sèches. Tapis gris clair.', dng:'—' },
  { id:'usnee', n:'Usnée barbue', lat:'Usnea barbata', e:'🍃', cat:'lichens', sub:'Lichens', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Pend des branches. Bio-indicateur d\'air pur.', dng:'—' },
  { id:'sphaigne', n:'Sphaigne', lat:'Sphagnum sp.', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Tourbières, zones humides. Forme la tourbe.', dng:'—' },
  { id:'polytric', n:'Polytric commun', lat:'Polytrichum commune', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Sous-bois humides, tourbières. Grande mousse dressée.', dng:'—' },

  { id:'machaon', n:'Machaon', lat:'Papilio machaon', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur ombellifères, adulte butineur.',
    hab:'Prairies fleuries, lisières. Grand papillon jaune-noir.', dng:'—' },
  { id:'petit_paon', n:'Paon-du-jour', lat:'Aglais io', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur orties, adulte sur fleurs.',
    hab:'Jardins, lisières. Ocelles bleus en forme d\'yeux.', dng:'—' },
  { id:'lucane', n:'Lucane cerf-volant', lat:'Lucanus cervus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Larve xylophage dans le bois mort de chêne.',
    hab:'Vieux chênes, bois mort. Plus grand coléoptère d\'Europe.', dng:'—' },
  { id:'carabe', n:'Carabe doré', lat:'Carabus auratus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédateur de limaces, vers, chenilles.',
    hab:'Sol des forêts et jardins. Reflets vert-doré.', dng:'—' },
  { id:'libellule', n:'Libellule déprimée', lat:'Libellula depressa', e:'🪰', cat:'insectes', sub:'Odonates', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédatrice de moucherons et moustiques.',
    hab:'Bords des lacs et mares. Abdomen large bleuté.', dng:'—' },
  { id:'bourdon', n:'Bourdon terrestre', lat:'Bombus terrestris', e:'🐝', cat:'insectes', sub:'Hyménoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nectar et pollen. Pollinisateur majeur.',
    hab:'Prairies, jardins. Niche au sol. Bande jaune.', dng:'Piqûre possible si menacé.' },

  // ═══ POISSONS ═══
  // tailleCm:[a,b] définit les trois paliers pêchés : petit <a, moyen a–b, grand >b
  { id:'brochet', n:'Brochet', lat:'Esox lucius', e:'🐟', cat:'poissons', sub:'Esocidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[], tailleCm:[50,80],
    alim:'Carnassier à l\'affût : perches, gardons, petits poissons, grenouilles.',
    hab:'Herbiers et eaux calmes des lacs et de la Līčupe.',
    dng:'Dents acérées — prudence en le décrochant.' },
  { id:'perche', n:'Perche commune', lat:'Perca fluviatilis', e:'🐟', cat:'poissons', sub:'Percidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[], tailleCm:[15,25],
    alim:'Alevins, larves, petits invertébrés aquatiques.',
    hab:'En bancs près des herbiers et des berges, lacs et rivière.',
    dng:'Nageoire dorsale épineuse — attention en la tenant.' },
  { id:'sandre', n:'Sandre', lat:'Sander lucioperca', e:'🐟', cat:'poissons', sub:'Percidés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[], tailleCm:[40,65],
    alim:'Carnassier crépusculaire : gardons, perches, petits poissons.',
    hab:'Eaux profondes et troubles des grands lacs.',
    dng:'Dents canines proéminentes — prudence.' },
  { id:'gardon', n:'Gardon', lat:'Rutilus rutilus', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[], tailleCm:[12,20],
    alim:'Algues, larves, petits invertébrés. Omnivore.',
    hab:'En bancs en eaux calmes, lacs et rivière.', dng:'—' },
  { id:'breme', n:'Brème commune', lat:'Abramis brama', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[], tailleCm:[25,40],
    alim:'Vers, larves, mollusques fouillés dans la vase.',
    hab:'Fonds vaseux des lacs calmes, en bancs.', dng:'—' },
  { id:'tanche', n:'Tanche', lat:'Tinca tinca', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[], tailleCm:[25,40],
    alim:'Vers, larves, végétation aquatique fouillés dans la vase.',
    hab:'Fonds vaseux et herbiers denses, eaux calmes.', dng:'—' },
  { id:'carassin', n:'Carassin commun', lat:'Carassius carassius', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[], tailleCm:[15,25],
    alim:'Végétation aquatique, larves, détritus.',
    hab:'Eaux calmes et peu profondes, tolère le manque d\'oxygène.', dng:'—' },

  // ═══ HUMAINS ═══
  { id:'h_ferdinand', n:'Ferdinand', lat:'Homo sapiens', e:'🧔', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Cueillette, potager, cidre maison. Omnivore opportuniste.',
    hab:'Migrateur saisonnier France ↔ Lettonie. Territoire estival étendu.',
    dng:'Aucun. Peut cependant lancer des chantiers imprévus.' },
  { id:'h_pierre', n:'Pierre', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Co-investisseur. Présence irrégulière.', dng:'Aucun.' },
  { id:'h_elena', n:'Elena', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présente sur la propriété.', dng:'Aucun.' },
  { id:'h_elena2', n:'Elena (2)', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_dasha', n:'Dasha', lat:'Homo sapiens', e:'👧', cat:'humains', sub:'Résidents', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présente sur la propriété.', dng:'Aucun.' },
  { id:'h_yanis', n:'Yanis', lat:'Homo sapiens', e:'👦', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_igor', n:'Igor', lat:'Homo sapiens', e:'👨', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_natacha', n:'Natacha', lat:'Homo sapiens', e:'👩‍🦰', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_natacha2', n:'Natacha (2)', lat:'Homo sapiens', e:'👩‍🦰', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_roman', n:'Roman', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présent sur la propriété.', dng:'Aucun.' },
  { id:'h_vanya', n:'Vanya', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_dasha2', n:'Dasha (2)', lat:'Homo sapiens', e:'👧', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteuse saisonnière. Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_loukas', n:'Loukas', lat:'Homo sapiens', e:'👦', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_anna', n:'Anna', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteuse saisonnière.', dng:'Aucun.' },
  { id:'h_cash', n:'Cash', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_gael', n:'Gaël', lat:'Homo sapiens', e:'🧔', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Aussi aperçu tenant un appareil photo, en train de cataloguer les autres espèces.', dng:'Aucun.' },

  // ═══ ANIMAUX DOMESTIQUES ═══
  { id:'d_sem', n:'Sem', lat:'Canis lupus familiaris', e:'🐕', cat:'domestiques', sub:'Chiens', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Croquettes, restes de table.', hab:'Vit sur la propriété.', dng:'Aucun.' },
  { id:'d_raya', n:'Raya', lat:'Canis lupus familiaris', e:'🐕', cat:'domestiques', sub:'Chiens', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Croquettes, restes de table.', hab:'Vit sur la propriété.', dng:'Aucun.' },
]

export const ACHIEVEMENTS = [
  // ── Paliers de recensement ──
  { e:'🌱', n:'Premiers pas',      d:'10 espèces observées',                w:'—', on:false, pts:60,  tier:1 },
  { e:'🌿', n:'Naturaliste',       d:'25 espèces observées',                w:'—', on:false, pts:150, tier:2 },
  { e:'🌳', n:'Connaisseur',       d:'50 espèces observées',                w:'—', on:false, pts:300, tier:3 },
  { e:'🏞️', n:'Encyclopédiste',    d:'80 espèces observées',                w:'—', on:false, pts:500, tier:4 },
  { e:'👑', n:'Maître du vivant',  d:'Toutes les espèces du Pokédex',       w:'—', on:false, pts:900, tier:5 },

  // ── Grands prédateurs & espèces difficiles ──
  { e:'🐆', n:'Le fantôme',        d:'Voir le lynx de ses propres yeux',    w:'—', on:false, pts:400 },
  { e:'🐺', n:'Trace de loup',     d:'Observer un loup ou identifier sa piste', w:'—', on:false, pts:350 },
  { e:'🐻', n:'L\'ours',           d:'Observer un ours brun',               w:'—', on:false, pts:600 },
  { e:'🌊', n:'La loutre',         d:'Observer une loutre sur la Līčupe',   w:'—', on:false, pts:280 },
  { e:'🦅', n:'Le pygargue',       d:'Observer un pygargue à queue blanche',w:'—', on:false, pts:220 },
  { e:'🦃', n:'Place de chant',    d:'Assister à la parade du grand tétras',w:'—', on:false, pts:450 },

  // ── Terrain difficile ──
  { e:'💀', n:'Charognard',        d:'Trouver une carcasse et identifier l\'espèce', w:'—', on:false, pts:180 },
  { e:'🥚', n:'Découvreur de nid', d:'Trouver 3 nids occupés d\'espèces différentes', w:'—', on:false, pts:200 },
  { e:'🕳️', n:'Cartographe souterrain', d:'Localiser 5 terriers ou gîtes actifs', w:'—', on:false, pts:250 },
  { e:'🦫', n:'Ingénieur du castor', d:'Trouver un barrage actif',          w:'—', on:false, pts:190 },
  { e:'🐾', n:'Pisteur',           d:'Identifier 10 empreintes d\'espèces différentes', w:'—', on:false, pts:230 },
  { e:'🍖', n:'Reste de repas',    d:'Trouver une proie mise en cache par un prédateur', w:'—', on:false, pts:320 },

  // ── Individus & suivi ──
  { e:'⭐', n:'Premier familier',  d:'Reconnaître et nommer un individu',   w:'—', on:false, pts:120 },
  { e:'🔖', n:'Le clan',           d:'Suivre 5 familiers différents',       w:'—', on:false, pts:280 },
  { e:'📅', n:'Fidélité',          d:'Revoir le même familier sur 3 saisons', w:'—', on:false, pts:340 },

  // ── Méthode ──
  { e:'👁️', n:'Œil de lynx',       d:'20 espèces vues à l\'œil nu',         w:'—', on:false, pts:260 },
  { e:'🌙', n:'Créature de la nuit', d:'10 espèces en vision nocturne',     w:'—', on:false, pts:240 },
  { e:'🏆', n:'Le grand chelem',   d:'Une espèce de chaque règne, à l\'œil nu', w:'—', on:false, pts:380 },
]

// points de badges par joueur
export function badgePts(playerName) {
  return ACHIEVEMENTS.filter(a => a.on && a.w.includes(playerName))
    .reduce((s, a) => s + (a.pts || 0), 0)
}

export function calcPts(sp, playerName) {
  const methods = sp.obs[playerName] || []
  if (!methods.length) return 0
  const best = methods.reduce((b, m) => (METHODS[m]?.mult || 0) > (METHODS[b]?.mult || 0) ? m : b, methods[0])
  const bonuses = sp.bonus[playerName] || []
  return Math.round(
    RARITY[sp.r].p * SIZE_MULT[sp.sz] * (METHODS[best]?.mult || 1) +
    (bonuses.includes('bebe') ? 20 : 0) +
    (bonuses.includes('terrier') ? 30 : 0)
  )
}
export function speciesPts(playerName) {
  return SPECIES.reduce((sum, sp) => sum + calcPts(sp, playerName), 0)
}
export function totalPts(playerName) {
  return speciesPts(playerName) + badgePts(playerName)
}
export function isObserved(sp) {
  return Object.values(sp.obs).some(v => v && v.length)
}
