// ═══════════════════════════════════════════════════════════════════
//  PLUDINI — Données · Espèces réelles de Lettonie / Vidzeme
// ═══════════════════════════════════════════════════════════════════

export const RARITY = {
  commun:      { l:'Commun',      p:5,   c:'#8B9B6E' },
  peu_commun:  { l:'Peu commun',  p:15,  c:'#C08A3E' },
  rare:        { l:'Rare',        p:40,  c:'#B5602F' },
  tres_rare:   { l:'Très rare',   p:100, c:'#8B3A2E' },
}

export const SIZE_MULT = { xs:1, s:1.5, m:2, l:2.5, xl:3 }

// multiplicateur de points selon la taille du poisson pêché (remplace la
// qualité de photo pour cette catégorie — trois paliers par espèce, définis
// via son champ tailleCm)
export const FISH_SIZE_MULT = { petit:1, moyen:1.6, grand:2.5 }

export const METHODS = {
  eye:   { l:'Vue directe',     mult:3,   c:'#4A5D32', on:'#EDE7D8' },
  scope: { l:'Longue-vue',      mult:2.5, c:'#6B7F4E', on:'#EDE7D8' },
  night: { l:'Vision nocturne', mult:2,   c:'#93A576', on:'#2B2620' },
  cam:   { l:'Caméra piège',    mult:1,   c:'#C3CDAE', on:'#3B4429' },
}

// ── États particuliers d'une observation (facultatif, mammifères/oiseaux) ──
// une observation taguée devient une "observation particulière" : contour
// bleu distinctif + bonus de points, et fait progresser la collection de
// badges de l'espèce (un badge par état déjà observé au moins une fois)
export const OBS_STATES = {
  bebe:   { l:'Bébé',   ru:'Детёныш', e:'👶' },
  maman:  { l:'Maman',  ru:'Мама',    e:'♀️' },
  papa:   { l:'Papa',   ru:'Папа',    e:'♂️' },
  vieux:  { l:'Vieux',  ru:'Старый',  e:'👴' },
  malade: { l:'Malade', ru:'Больной', e:'🤒' },
  gite:   { l:'Terrier', ru:'Нора', e:'🕳️', lBird:'Nid', ruBird:'Гнездо', eBird:'🪺' },
}
// même principe que OBS_STATES, mais pour les arbres : ce qui a été observé/
// photographié n'est pas un "état" de l'animal mais la partie de l'arbre qui
// permet de l'identifier
export const TREE_PARTS = {
  ecorce:     { l:'Écorce',       ru:'Кора',    e:'🪵' },
  feuille:    { l:'Feuille',      ru:'Лист',    e:'🍃' },
  fleur:      { l:'Fleur',        ru:'Цветок',  e:'🌸' },
  fruit:      { l:'Fruit/graine', ru:'Плод',    e:'🌰' },
  coupe:      { l:'Coupe/tronc',  ru:'Спил',    e:'🪓' },
  silhouette: { l:'Silhouette',   ru:'Силуэт',  e:'🌳' },
}
export const OBS_STATE_BONUS_MULT = 1.1
export const OBS_STATE_COLOR = '#3E6B8C'

// ── Couleur par observateur — sert à border les vignettes d'observation pour
// reconnaître qui a vu quoi d'un coup d'œil. Dérivée du rang du joueur dans la
// liste (stable : un joueur n'est jamais réordonné, seulement ajouté en fin)
// plutôt que stockée, pour n'exiger aucune migration à l'ajout d'un joueur ──
const PLAYER_PALETTE = [
  '#B5602F', '#3E6B8C', '#6B7F4E', '#9C5B8C', '#C08A3E',
  '#4F8C7A', '#8C4F4F', '#5C6B8C', '#7A8B3E', '#A34E7A',
]
export function playerColor(name, players) {
  const idx = players.findIndex(p => p.name === name)
  return PLAYER_PALETTE[(idx < 0 ? 0 : idx) % PLAYER_PALETTE.length]
}

// le jeu d'états/parties applicable à une espèce, selon son règne — null si
// cette espèce ne se prête pas à ce système (insectes, poissons, humains…)
export function statesFor(sp) {
  if (['mammiferes','oiseaux'].includes(sp?.cat)) return OBS_STATES
  if (sp?.cat === 'arbres') return TREE_PARTS
  return null
}

// libellé d'un état contextualisé à l'espèce : le gîte se présente comme un
// terrier chez les mammifères, un nid chez les oiseaux
export function obsStateLabel(key, sp) {
  const st = statesFor(sp)?.[key]
  if (!st) return null
  const bird = sp?.cat === 'oiseaux'
  return { l: (bird && st.lBird) || st.l, ru: (bird && st.ruBird) || st.ru, e: (bird && st.eBird) || st.e }
}

export const PLAYERS = [
  { id:'G', name:'Gaël' },
  { id:'P', name:'Pierre' },
  { id:'E', name:'Elena' },
  { id:'F', name:'Ferdinand' },
]

export const CATS = [
  { id:'mammiferes', e:'🦁', n:'Mammifères', lat:'Mammalia',
    niche:"Les mammifères de la propriété se répartissent la nuit et le sol : les uns creusent (blaireau, castor), les autres arpentent en silence à l'aube et au crépuscule (chevreuil, renard), d'autres encore grimpent dans les frondaisons (écureuil, martre). Cette différenciation de l'espace et de l'horaire — plutôt que de la nourriture — leur permet de coexister sans se concurrencer directement.",
    subs:[
      { id:'Cervidés', lat:'Cervidae',
        niche:"Les grands herbivores du domaine — élan, cerf, chevreuil — se répartissent la forêt par gabarit : le plus grand accède aux ressources les plus hautes ou les plus difficiles, le plus petit se rabat sur un régime plus sélectif. Leur bois, renouvelé chaque année, sert aussi de repère saisonnier fiable sur les caméras." },
      { id:'Canidés', lat:'Canidae',
        niche:"Prédateurs généralistes et opportunistes, du renard au loup, ils s'adaptent à presque toutes les proies et tous les horaires — ce qui leur permet de rester actifs toute l'année là où des espèces plus spécialisées doivent migrer ou hiberner." },
      { id:'Félidés', lat:'Felidae',
        niche:"Chasseurs solitaires à l'affût plutôt qu'à la course, lynx et chat sauvage misent sur la discrétion et le camouflage dans le sous-bois dense, là où la vitesse pure ne suffit pas." },
      { id:'Mustélidés', lat:'Mustelidae',
        niche:"De la blairaudière du blaireau aux berges de la loutre, cette famille très diverse en taille et en régime occupe presque tous les milieux du domaine — chacun creusant sa propre niche, du sol à l'eau, avec un minimum de concurrence entre eux." },
      { id:'Rongeurs', lat:'Rodentia / Lagomorpha',
        niche:"Petits et prolifiques, écureuil, lièvre et castor exploitent des ressources que les grands herbivores ignorent — graines de cônes, écorce tendre, plantes aquatiques — et forment la base du régime de presque tous les prédateurs du domaine." },
      { id:'Autres', lat:'Erinaceidae / Suidae',
        niche:"Un groupe hétérogène — sanglier fouisseur, hérisson insectivore nocturne — réuni ici par défaut, chacun occupant une niche bien à lui, sans lien de parenté proche entre eux." },
  ]},
  { id:'oiseaux', e:'🦅', n:'Oiseaux', lat:'Aves',
    niche:"Chaque espèce d'oiseau exploite une tranche verticale ou horaire différente de la forêt : le pic creuse le bois mort, la mésange fouille les brindilles, le pygargue plane au-dessus des lacs, la hulotte chasse quand tous les autres dorment. En se répartissant ainsi la canopée, le sous-bois et l'air, ils évitent de se marcher dessus.",
    subs:[
      { id:'Gruidés', lat:'Gruidae',
        niche:"Grands échassiers migrateurs, les grues n'occupent les zones humides du domaine qu'une partie de l'année — une niche mobile qui suit les saisons plutôt que d'y rester fixée." },
      { id:'Strigidés', lat:'Strigidae',
        niche:"Rapaces nocturnes, les chouettes et hiboux chassent les mêmes petits mammifères que les rapaces diurnes, mais de nuit — un partage temporel qui évite toute concurrence directe." },
      { id:'Picidés', lat:'Picidae',
        niche:"En creusant le bois mort pour atteindre les larves xylophages, les pics façonnent des cavités qui serviront ensuite d'abri à bien d'autres espèces — un rôle d'ingénieur forestier." },
      { id:'Accipitridés', lat:'Accipitridae',
        niche:"Rapaces diurnes de tailles très variées, du pygargue au-dessus des lacs à la buse au-dessus des champs, ils dominent l'espace aérien en plein jour, chacun sur son propre terrain de chasse." },
      { id:'Ciconiidés', lat:'Ciconiidae',
        niche:"Grands échassiers discrets des zones humides forestières les plus isolées, à l'opposé de la cigogne blanche qui recherche la proximité humaine." },
      { id:'Corvidés', lat:'Corvidae',
        niche:"Intelligents et opportunistes, les corvidés comme le geai stockent des réserves de glands qu'ils oublient en partie — participant, sans le vouloir, à la régénération de la forêt." },
      { id:'Tétraonidés', lat:'Tetraonidae',
        niche:"Gallinacés forestiers, le grand tétras se nourrit presque exclusivement d'aiguilles de pin en hiver — une ressource abondante mais indigeste que peu d'autres espèces savent exploiter." },
      { id:'Paridés', lat:'Paridae',
        niche:"Petits passereaux très actifs, les mésanges fouillent le feuillage à la recherche d'insectes minuscules, puis basculent sur les graines en hiver — une flexibilité qui leur permet de rester visibles toute l'année." },
      { id:'Muscicapidés', lat:'Muscicapidae',
        niche:"Passereaux insectivores au sol, comme le rougegorge, ils chassent dans la litière et le sous-bois — une strate basse que la plupart des autres oiseaux négligent." },
      { id:'Alcédinidés', lat:'Alcedinidae',
        niche:"Spécialiste ultra-précis, le martin-pêcheur plonge en piqué pour capturer de petits poissons — une technique qui ne lui laisse presque aucun concurrent parmi les oiseaux du domaine." },
      { id:'Anatidés', lat:'Anatidae',
        niche:"Oiseaux d'eau de grande taille, les cygnes atteignent avec leur long cou des plantes aquatiques immergées hors de portée des canards plus petits." },
      { id:'Fringillidés', lat:'Fringillidae',
        niche:"Granivores le reste de l'année, les pinsons basculent sur les insectes en période de nidification pour nourrir leurs jeunes en protéines." },
      { id:'Columbidés', lat:'Columbidae',
        niche:"Grâce à un jabot extensible, les pigeons peuvent avaler et stocker de grandes quantités de graines ou de glands en une seule fois — une capacité que les petits passereaux n'ont pas." },
  ]},
  { id:'arbres', e:'🌳', n:'Arbres', lat:'Arbores',
    niche:"Les arbres se disputent la lumière plus que tout : le pin colonise les sols pauvres et secs où rien d'autre ne pousse, l'aulne s'installe les pieds dans l'eau des berges, le hêtre attend patiemment à l'ombre des autres avant de percer la canopée. Chaque essence a trouvé le sol, l'humidité ou la patience que les autres n'avaient pas.",
    subs:[
      { id:'Fagacées', lat:'Fagaceae' }, { id:'Bétulacées', lat:'Betulaceae' },
      { id:'Pinacées', lat:'Pinaceae' }, { id:'Salicacées', lat:'Salicaceae' },
      { id:'Rosacées', lat:'Rosaceae' }, { id:'Sapindacées', lat:'Sapindaceae' },
      { id:'Malvacées', lat:'Malvaceae' },
  ]},
  { id:'arbustes', e:'🌿', n:'Arbustes', lat:'Frutices',
    niche:"Coincés entre le sol et la canopée, les arbustes occupent l'étage intermédiaire que les arbres laissent vide : ils fleurissent tôt avant que les feuillus ne fassent de l'ombre, ou tolèrent les sols acides et pauvres des sous-bois où peu d'autres plantes s'installent.",
    subs:[
      { id:'Éléagnacées', lat:'Elaeagnaceae' }, { id:'Éricacées', lat:'Ericaceae' },
      { id:'Bétulacées', lat:'Betulaceae' }, { id:'Rosacées', lat:'Rosaceae' },
      { id:'Adoxacées', lat:'Adoxaceae' }, { id:'Cupressacées', lat:'Cupressaceae' },
  ]},
  { id:'champignons', e:'🍄', n:'Champignons', lat:'Fungi',
    niche:"Invisibles la majeure partie de l'année, les champignons occupent une niche que ni plante ni animal ne peut remplir : certains vivent en symbiose souterraine avec les racines d'un arbre précis, d'autres décomposent le bois mort ou la litière que personne d'autre ne digère. Ils recyclent ce que la forêt ne peut pas utiliser autrement.",
    subs:[
      { id:'Bolétales', lat:'Boletales' }, { id:'Agaricales', lat:'Agaricales' },
      { id:'Russulales', lat:'Russulales' }, { id:'Cantharellales', lat:'Cantharellales' },
      { id:'Polypores', lat:'Polyporales' },
  ]},
  { id:'lichens', e:'🍃', n:'Lichens & mousses', lat:'Lichenes / Bryophyta',
    niche:"Les lichens et mousses colonisent l'écorce nue, la roche ou le sol acide que rien de plus grand ne peut exploiter — sans racines, sans besoin de sol riche, juste de l'air et de la pluie. Leur simple présence, ou absence, indique la qualité de l'air : une niche que même les plantes à racines ne peuvent occuper.",
    subs:[
      { id:'Lichens', lat:'Lichenes' }, { id:'Mousses', lat:'Bryophyta' },
  ]},
  { id:'humains', e:'🧍', n:'Humains', lat:'Homo sapiens', subs:[
      { id:'Résidents', lat:'Hominidae · permanents' },
      { id:'Travailleurs', lat:'Hominidae · sur place' },
      { id:'Visiteurs', lat:'Hominidae · saisonniers' },
  ]},
  { id:'domestiques', e:'🐾', n:'Animaux domestiques', lat:'Animalia domestica', subs:[
      { id:'Chiens', lat:'Canis lupus familiaris' },
      { id:'Chats', lat:'Felis catus' },
  ]},
  { id:'insectes', e:'🦋', n:'Insectes', lat:'Insecta',
    niche:"En quelques millimètres, les insectes se répartissent des niches invisibles à l'œil nu : le carabe chasse au sol la nuit, la libellule patrouille au-dessus de l'eau, le bourdon butine tôt le matin quand les fleurs sont encore fraîches. Leur petite taille leur permet d'exploiter des ressources bien trop fines pour tout autre animal du domaine.",
    subs:[
      { id:'Lépidoptères', lat:'Lepidoptera',
        niche:"Chaque papillon est lié à une plante hôte précise pour sa chenille — ombellifères, orties — ce qui répartit naturellement la ressource entre espèces sans concurrence directe." },
      { id:'Coléoptères', lat:'Coleoptera',
        niche:"Des géants comme le lucane, dont la larve se développe des années dans le bois mort, aux petits prédateurs nocturnes comme le carabe, ce groupe couvre presque tous les rôles écologiques du sol forestier." },
      { id:'Odonates', lat:'Odonata',
        niche:"Les libellules vivent deux vies successives : larve aquatique prédatrice pendant des mois, puis chasseuse aérienne de moucherons — un cycle qui leur fait exploiter deux milieux à la fois." },
      { id:'Hyménoptères', lat:'Hymenoptera',
        niche:"Pollinisateurs capables de réchauffer leur corps par vibration musculaire, les bourdons butinent par temps frais ou tôt le matin, quand les abeilles restent encore à la ruche." },
  ]},
  { id:'poissons', e:'🐟', n:'Poissons', lat:'Pisces',
    niche:"Dans un même lac, chaque poisson occupe une strate d'eau différente : le gardon en surface, la perche près des herbiers, le brochet à l'affût immobile, la brème et la tanche fouillant la vase du fond. Cette répartition verticale évite que tous se disputent la même proie au même endroit.",
    subs:[
      { id:'Esocidés', lat:'Esocidae',
        niche:"Le brochet chasse à l'affût, immobile dans les herbiers — une stratégie de guet qui l'installe au sommet de la chaîne alimentaire des lacs et de la Līčupe." },
      { id:'Percidés', lat:'Percidae',
        niche:"Perche et sandre chassent activement plutôt qu'à l'affût, l'une en bancs près des berges de jour, l'autre seule dans les eaux profondes au crépuscule." },
      { id:'Cyprinidés', lat:'Cyprinidae',
        niche:"Le groupe le plus nombreux et le plus tolérant du domaine — gardon, brème, tanche, carassin — capable de survivre dans des eaux pauvres en oxygène où les carnassiers ne s'aventurent pas." },
  ]},
  { id:'batraciens', e:'🐸', n:'Batraciens', lat:'Amphibia',
    niche:"Les batraciens exploitent une niche que presque aucun autre vertébré du domaine ne partage : une peau perméable qui respire et absorbe l'eau, mais qui les oblige à rester en milieu humide et à retourner à l'eau pour se reproduire. Cette double vie, terrestre et aquatique, en fait un maillon essentiel entre les deux mondes — et un indicateur précoce de la qualité de l'eau et de l'air.",
    subs:[
      { id:'Bufonidés', lat:'Bufonidae',
        niche:"Le crapaud mène une double vie amphibie qu'aucun mammifère ou oiseau ne partage : terrestre et nocturne la majeure partie de l'année, aquatique au printemps pour se reproduire." },
      { id:'Ranidés', lat:'Ranidae',
        niche:"Les grenouilles restent bien plus liées à l'eau que les crapauds, ne s'en éloignant guère au-delà des berges et des zones humides." },
      { id:'Salamandridés', lat:'Salamandridae',
        niche:"Amphibiens discrets des sous-bois humides et frais, les salamandres et tritons se signalent souvent par leurs couleurs vives, un avertissement chimique plutôt qu'un camouflage." },
  ]},
]

export const SPECIES = [
  { id:'elan', n:'Élan', lat:'Alces alces', e:'🫎', cat:'mammiferes', sub:'Cervidés', r:'rare', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    anecdote:"L'élan est le plus grand cervidé du monde : un mâle adulte peut atteindre 800 kg. Il nage remarquablement bien et peut plonger jusqu'à 5 m pour atteindre des plantes aquatiques. Ses longues pattes lui permettent de traverser 1 m de neige sans effort.",
    saisons:{printemps:'Mise bas en mai-juin. Les femelles deviennent très défensives.',ete:'Fréquente les zones humides pour se nourrir et échapper aux insectes.',automne:'Rut en septembre-octobre. Les mâles deviennent imprévisibles.',hiver:'Se rabat sur les jeunes pousses de saule et bouleau. Perd ses bois.'},
    alim:'Saule, bouleau, plantes aquatiques. 20–30 kg/jour.',
    hab:'Zones humides, lisières. Territoire 10–30 km². Solitaire.',
    dng:'Femelle avec veau dangereuse. Mâle imprévisible en rut (sept–oct).',
    niche:"Ses longues pattes lui donnent accès aux plantes aquatiques immergées et aux zones humides impraticables pour les autres cervidés — une ressource que son gabarit et sa hauteur sont seuls à pouvoir exploiter." },
  { id:'cerf', n:'Cerf élaphe', lat:'Cervus elaphus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le brame du cerf porte à plus de 5 km par nuit calme. Les bois repoussent chaque année à raison de 2 cm par jour — c'est le tissu à croissance la plus rapide du règne animal.",
    saisons:{printemps:'Chute des bois puis repousse sous velours. Naissance des faons en mai-juin.',ete:'Pelage roux vif. Vie en hardes séparées mâles/femelles.',automne:'Le brame. Les mâles rassemblent leurs harems et combattent.',hiver:'Pelage gris épais. Regroupements pour économiser l\'énergie.'},
    alim:'Herbes, baies, glands, champignons, écorce.',
    hab:'Forêt et lisières. Sociable en hardes.', dng:'Aucun danger hors rut.',
    niche:"Sa taille et son système digestif lui permettent de digérer une végétation plus grossière et fibreuse que le chevreuil, plus petit et sélectif — les deux cervidés se partagent ainsi la même forêt sans se concurrencer." },
  { id:'chevreuil', n:'Chevreuil', lat:'Capreolus capreolus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le chevreuil est le seul ongulé à pratiquer la diapause embryonnaire : fécondé en juillet, l'embryon ne s'implante qu'en décembre. L'aboiement qu'on entend en forêt, c'est lui — un cri d'alarme sec qui prévient tout le voisinage.",
    saisons:{printemps:'Naissance des faons en mai. Bois débarrassés du velours.',ete:'Rut en juillet-août. Poursuites en cercles caractéristiques.',automne:'Pelage gris-brun. Constitution des réserves.',hiver:'Regroupement en petites hardes. Chute des bois en octobre-novembre.'},
    alim:'Pousses, baies, champignons, lierre. Sélectif.',
    hab:'Lisières et clairières. Territoire 30–60 ha.', dng:'Aucun.',
    niche:"Trop petit pour se nourrir de grandes quantités de végétation grossière, il compense par un régime très sélectif — bourgeons, jeunes pousses — qui lui permet de vivre sur des surfaces bien plus réduites que le cerf ou l'élan." },
  { id:'sanglier', n:'Sanglier', lat:'Sus scrofa', e:'🐗', cat:'mammiferes', sub:'Autres', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Racines, glands, vers, larves, charognes. Omnivore.',
    hab:'Forêt dense, souilles près de l\'eau. En compagnies.',
    dng:'Laie avec marcassins agressive. Peut charger.',
    niche:"En retournant la terre avec son groin, il accède à des vers, larves et racines enfouis que les autres mammifères de la forêt ne peuvent atteindre — une source d'énergie souterraine qui lui est presque exclusive." },
  { id:'renard', n:'Renard roux', lat:'Vulpes vulpes', e:'🦊', cat:'mammiferes', sub:'Canidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le renard utilise le champ magnétique terrestre pour chasser : il oriente son bond nord-est et réussit 73 % de ses attaques dans cet axe, contre 18 % dans les autres directions. Il possède plus de 20 vocalisations différentes.",
    saisons:{printemps:'Naissance des renardeaux en avril. Les adultes chassent en permanence.',ete:'Émancipation progressive des jeunes. Régime riche en fruits et insectes.',automne:'Dispersion des jeunes. Constitution des réserves de graisse.',hiver:'Rut en janvier-février. Cris nocturnes caractéristiques.'},
    alim:'Rongeurs, lapins, oeufs, fruits, insectes.',
    hab:'Lisières, bocage. Terrier actif sur la propriété.',
    dng:'La gale sarcoptique est contagieuse pour le chien — surveiller si un individu semble dégarni.',
    niche:"Généraliste, il exploite une gamme de proies et d'horaires plus large qu'aucun autre prédateur du domaine — rongeurs à l'aube, fruits en été, charognes en hiver — ce qui lui permet de rester actif toute l'année là où les spécialistes doivent migrer ou hiberner." },
  { id:'loup', n:'Loup gris', lat:'Canis lupus', e:'🐺', cat:'mammiferes', sub:'Canidés', r:'tres_rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Cerf, chevreuil, sanglier, castor. Chasse en meute.',
    hab:'Grands massifs forestiers. Territoire 100–300 km².',
    dng:'Très craintif envers l\'humain. Surveille les chiens.',
    niche:"Seul prédateur capable d'abattre régulièrement de grands ongulés comme le cerf ou le sanglier adulte, il occupe le sommet de la chaîne alimentaire — une place qu'aucune autre espèce du domaine ne peut revendiquer." },
  { id:'viverrin', n:'Chien viverrin', lat:'Nyctereutes procyonoides', e:'🦝', cat:'mammiferes', sub:'Canidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Grenouilles, poissons, baies, rongeurs, charognes.',
    hab:'Zones humides. Espèce invasive. Torpeur hivernale.',
    dng:'⚠️ Vecteur de rage. Danger pour la basse-cour.',
    niche:"Seul canidé d'Europe à entrer en torpeur hivernale, il exploite les zones humides et leurs amphibiens à une période où la plupart des autres prédateurs sont contraints à l'inactivité ou à la migration." },
  { id:'lynx', n:'Lynx boréal', lat:'Lynx lynx', e:'🐆', cat:'mammiferes', sub:'Félidés', r:'tres_rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    anecdote:"Le lynx ne rugit pas : il miaule, ronronne et pousse des cris rauques. En Lettonie, la population est passée de moins de 100 individus dans les années 1950 à environ 1 200 aujourd'hui. Il peut bondir sur 7 mètres d'un seul élan.",
    saisons:{printemps:'Mise bas en mai. La femelle reste cantonnée près de la tanière.',ete:'Élevage des jeunes. Chasse plus fréquente pour nourrir la portée.',automne:'Les jeunes accompagnent la mère. Territoire parcouru intensément.',hiver:'Rut en février-mars. Traces bien visibles dans la neige.'},
    alim:'Chevreuil (70–80%), cerf, lièvre. Affût et bond.',
    hab:'Forêt dense. Territoire 200–500 km². Solitaire.',
    dng:'Aucun pour l\'humain. Très craintif.',
    niche:"Chasseur à l'affût plutôt qu'à la course, il exploite le sous-bois dense où sa discrétion lui donne un avantage que les prédateurs plus rapides mais moins furtifs, comme le loup, n'ont pas." },
  { id:'chat_sauvage', n:'Chat sauvage', lat:'Felis silvestris', e:'🐈', cat:'mammiferes', sub:'Félidés', r:'rare', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Rongeurs, oiseaux, lapereaux.',
    hab:'Forêt de feuillus, lisières broussailleuses. Discret.', dng:'Aucun. Fuit l\'humain.',
    niche:"Petit prédateur solitaire, il chasse dans les fourrés denses et les lisières broussailleuses où sa petite taille et sa discrétion lui permettent de capturer des rongeurs sans concurrencer les prédateurs plus grands." },
  { id:'blaireau', n:'Blaireau européen', lat:'Meles meles', e:'🦡', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Vers de terre (80%), baies, insectes, rongeurs.',
    hab:'Blairaudière multigénérationnelle. Torpeur hivernale.', dng:'Inoffensif.',
    niche:"Il creuse un terrier multigénérationnel qui peut s'étendre sur des dizaines de mètres — un espace souterrain qu'aucun autre mammifère de la propriété n'exploite aussi durablement. Son régime, dominé à 80% par les vers de terre, cible une ressource que peu d'autres prédateurs jugent rentable de chercher." },
  { id:'martre', n:'Martre des pins', lat:'Martes martes', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Rongeurs, oiseaux, oeufs, baies, miel.',
    hab:'Forêt de conifères et mixte. Arboricole.', dng:'Aucun pour l\'humain.',
    niche:"Grimpeuse agile, elle chasse dans la canopée et les cavités des arbres — un espace vertical que les prédateurs terrestres comme le renard ou le putois ne peuvent atteindre." },
  { id:'putois', n:'Putois d\'Europe', lat:'Mustela putorius', e:'🦨', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, rongeurs, oiseaux.',
    hab:'Zones humides, lisières, granges.', dng:'Aucun.',
    niche:"Chasseur nocturne des zones humides, il cible les amphibiens à un moment et dans un habitat où la concurrence des autres mustélidés, plus terrestres ou diurnes, reste minimale." },
  { id:'hermine', n:'Hermine', lat:'Mustela erminea', e:'🐁', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, lapereaux.',
    hab:'Lisières, murets, prairies. Blanche en hiver.', dng:'Aucun.',
    niche:"Assez fine pour s'enfoncer dans les galeries des campagnols et les y poursuivre, elle exploite une ressource inaccessible aux prédateurs plus grands — et son pelage blanchit l'hiver pour rester invisible sur la neige." },
  { id:'loutre', n:'Loutre d\'Europe', lat:'Lutra lutra', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, écrevisses.',
    hab:'Rivière Līčupe, berges des lacs. Marque avec épreintes.', dng:'Aucun.',
    niche:"Seul mustélidé du domaine véritablement inféodé à l'eau, elle exploite les poissons et écrevisses de la Līčupe et des lacs — une ressource aquatique que ni le putois ni la martre ne peuvent exploiter." },
  { id:'vison', n:'Vison d\'Europe', lat:'Mustela lutreola', e:'🦫', cat:'mammiferes', sub:'Mustélidés', r:'tres_rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, poissons, petits rongeurs.',
    hab:'Berges des cours d\'eau. Très menacé en Europe.', dng:'Aucun.',
    niche:"Minuscule et inféodé aux berges des cours d'eau, il occupe une niche si étroite — entre l'eau et la terre, entre petits poissons et rongeurs — que la moindre perturbation de ce milieu suffit à le faire disparaître, ce qui en fait l'un des mammifères les plus menacés d'Europe." },
  { id:'castor', n:'Castor d\'Eurasie', lat:'Castor fiber', e:'🦫', cat:'mammiferes', sub:'Rongeurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce, rameaux, plantes aquatiques.',
    hab:'Līčupe et lacs. Construit huttes et barrages.', dng:'Aucun.',
    niche:"Seul mammifère du domaine capable de transformer son propre habitat : en construisant huttes et barrages, il crée des zones humides qui profitent ensuite à des dizaines d'autres espèces — une niche d'ingénieur de l'écosystème." },
  { id:'ecureuil', n:'Écureuil roux', lat:'Sciurus vulgaris', e:'🐿️', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de conifères, noisettes, glands, champignons.',
    hab:'Forêt de conifères et mixte. Arboricole diurne.', dng:'Aucun.',
    niche:"Actif de jour dans la canopée des conifères, il exploite les graines des cônes avant même qu'elles ne tombent au sol — une ressource hors de portée des rongeurs terrestres nocturnes comme le mulot." },
  { id:'lievre', n:'Lièvre d\'Europe', lat:'Lepus europaeus', e:'🐇', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Herbes, écorces, cultures.',
    hab:'Champs, lisières, prairies. Gîte à découvert.', dng:'Aucun.',
    niche:"Contrairement à un lapin, il ne creuse pas de terrier : il mise sur la vitesse et le camouflage à découvert, dans les champs et prairies — un espace ouvert que les autres mammifères, plus discrets, évitent." },
  { id:'herisson', n:'Hérisson', lat:'Erinaceus europaeus', e:'🦔', cat:'mammiferes', sub:'Autres', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, limaces, oeufs.',
    hab:'Jardins, lisières, haies. Nocturne. Hiberne.', dng:'Aucun.',
    niche:"Nocturne et insectivore, il fouille la litière des haies et jardins pour des proies que les oiseaux diurnes ne voient jamais — puis hiberne tout l'hiver pour éviter la période où cette ressource disparaît." },

  { id:'grue', n:'Grue cendrée', lat:'Grus grus', e:'🪽', cat:'oiseaux', sub:'Gruidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Grains, insectes, vers, amphibiens.',
    hab:'Zones humides. Migratrice. Parade nuptiale spectaculaire.', dng:'Aucun.',
    niche:"Migratrice, elle n'exploite les zones humides du domaine qu'une partie de l'année, laissant la place à d'autres espèces le reste du temps — une niche qui se déplace avec les saisons plutôt que de rester fixe." },
  { id:'hulotte', n:'Chouette hulotte', lat:'Strix aluco', e:'🦉', cat:'oiseaux', sub:'Strigidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, oiseaux, amphibiens.',
    hab:'Forêt mixte, vieux arbres à cavités. Nocturne.', dng:'Aucun.',
    niche:"En chassant la nuit, elle capture les campagnols et mulots à l'heure où la buse, son équivalent diurne, est inactive — les deux rapaces se partagent ainsi les mêmes proies sans jamais se croiser." },
  { id:'pic_noir', n:'Pic noir', lat:'Dryocopus martius', e:'🐦‍⬛', cat:'oiseaux', sub:'Picidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Fourmis, larves xylophages sous l\'écorce.',
    hab:'Vieilles forêts de conifères. Plus grand pic d\'Europe.', dng:'Aucun.',
    niche:"Seul capable de creuser aussi profondément dans le bois mort pour atteindre les larves xylophages, il façonne aussi, sans le savoir, les cavités que d'autres espèces — chouettes, martres — occuperont ensuite." },
  { id:'pygargue', n:'Pygargue à queue blanche', lat:'Haliaeetus albicilla', e:'🦅', cat:'oiseaux', sub:'Accipitridés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, oiseaux d\'eau, charognes.',
    hab:'Grands lacs, envergure jusqu\'à 2,4m.', dng:'Aucun.',
    niche:"Avec une envergure atteignant 2,4 m, il domine l'espace aérien au-dessus des grands lacs — une échelle et une portée de vol qu'aucun autre rapace du domaine n'atteint." },
  { id:'cigogne_noire', n:'Cigogne noire', lat:'Ciconia nigra', e:'🐦', cat:'oiseaux', sub:'Ciconiidés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, insectes aquatiques.',
    hab:'Forêts humides isolées. Très discrète, farouche.', dng:'Aucun.',
    niche:"Contrairement à la cigogne blanche qui recherche la proximité humaine, elle exploite les zones humides forestières les plus isolées — une niche de discrétion que peu d'autres grands échassiers occupent." },
  { id:'geai', n:'Geai des chênes', lat:'Garrulus glandarius', e:'🐦', cat:'oiseaux', sub:'Corvidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands, faines, insectes, oeufs.',
    hab:'Forêts de feuillus. Sentinelle bruyante de la forêt.', dng:'Aucun.',
    niche:"En enterrant des milliers de glands chaque automne pour se constituer des réserves — puis en oubliant une partie d'entre eux — il participe activement à la régénération des chênaies, un rôle qu'aucun autre oiseau du domaine ne joue à cette échelle." },
  { id:'grand_tetras', n:'Grand tétras', lat:'Tetrao urogallus', e:'🦃', cat:'oiseaux', sub:'Tétraonidés', r:'tres_rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles de pin, baies, bourgeons.',
    hab:'Vieilles pinèdes. Parade au chant.', dng:'Mâle en parade peut charger.',
    niche:"Il est l'un des seuls oiseaux capables de se nourrir presque exclusivement d'aiguilles de pin en hiver — une ressource abondante mais indigeste que la plupart des autres espèces ne peuvent exploiter." },
  { id:'mesange', n:'Mésange charbonnière', lat:'Parus major', e:'🐦', cat:'oiseaux', sub:'Paridés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, graines, chenilles.',
    hab:'Jardins, lisières, mangeoires en hiver.', dng:'Aucun.',
    niche:"Elle fouille les brindilles et le feuillage à la recherche d'insectes minuscules invisibles aux prédateurs plus grands, puis bascule sur les graines en hiver — une flexibilité qui lui permet de rester active toute l'année." },
  { id:'rougegorge', n:'Rougegorge familier', lat:'Erithacus rubecula', e:'🐦', cat:'oiseaux', sub:'Muscicapidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, baies.',
    hab:'Sous-bois, haies. Chant matinal caractéristique.', dng:'Aucun.',
    niche:"Il chasse au ras du sol, dans la litière et les sous-bois, une strate basse que la plupart des autres passereaux, plus arboricoles, négligent." },
  { id:'buse', n:'Buse variable', lat:'Buteo buteo', e:'🦅', cat:'oiseaux', sub:'Accipitridés', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, rongeurs, charognes.',
    hab:'Lisières, poteaux, vol en cercles au-dessus des champs.', dng:'Aucun.',
    niche:"En planant en cercles au-dessus des champs ouverts, elle repère les campagnols à découvert — un terrain de chasse aérien diurne que la hulotte, nocturne, laisse totalement libre." },
  { id:'martin_pecheur', n:'Martin-pêcheur d\'Europe', lat:'Alcedo atthis', e:'🐦', cat:'oiseaux', sub:'Alcédinidés', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Petits poissons, pêchés en piqué.',
    hab:'Berges de la Līčupe et des lacs. Plumage bleu vif.', dng:'Aucun.',
    niche:"Spécialiste absolu, il plonge en piqué pour capturer de petits poissons près de la surface — une technique si précise qu'elle ne lui laisse quasiment aucun concurrent parmi les autres oiseaux du domaine." },
  { id:'cygne', n:'Cygne tuberculé', lat:'Cygnus olor', e:'🦢', cat:'oiseaux', sub:'Anatidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Plantes aquatiques, algues.',
    hab:'Grands lacs du territoire. Couples fidèles à vie.', dng:'Peut charger près du nid.',
    niche:"Son long cou lui permet d'atteindre les plantes aquatiques immergées à des profondeurs hors de portée des canards et autres oiseaux d'eau plus petits." },
  { id:'pinson', n:'Pinson des arbres', lat:'Fringilla coelebs', e:'🐦', cat:'oiseaux', sub:'Fringillidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines, insectes en période de nidification.',
    hab:'Forêts, lisières, jardins. Chant vif et répétitif.', dng:'Aucun.',
    niche:"Granivore le reste de l'année, il bascule sur les insectes en période de nidification pour nourrir ses jeunes en protéines — une flexibilité alimentaire saisonnière qui lui évite de dépendre d'une seule ressource." },
  { id:'pigeon_ramier', n:'Pigeon ramier', lat:'Columba palumbus', e:'🐦', cat:'oiseaux', sub:'Columbidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines, bourgeons, feuilles, glands.',
    hab:'Forêts, lisières, sol dégagé. Vol bruyant au décollage.', dng:'Aucun.',
    niche:"Sa taille et son jabot extensible lui permettent d'avaler et de stocker de grandes quantités de glands ou de bourgeons en une seule fois — une capacité que les petits passereaux granivores n'ont pas." },

  { id:'chene', n:'Chêne pédonculé', lat:'Quercus robur', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands = nourriture clé pour sanglier, geai, écureuil.',
    hab:'Forêts de feuillus, sols riches. Peut vivre 500+ ans.', dng:'—',
    niche:"Sa racine pivotante profonde lui permet d'exploiter l'eau et les nutriments des sols riches là où peu d'autres arbres tiennent aussi longtemps — jusqu'à 500 ans — devenant au passage une ressource alimentaire clé pour des dizaines d'espèces." },
  { id:'hetre', n:'Hêtre commun', lat:'Fagus sylvatica', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Faines consommées par de nombreux animaux.',
    hab:'Forêts denses, sols frais. Écorce lisse grise.', dng:'—',
    niche:"Il germe et patiente à l'ombre des autres arbres pendant des décennies, tolérant un manque de lumière qui tuerait la plupart des essences pionnières — puis projette à son tour une ombre si dense qu'elle empêche la concurrence de s'installer sous lui." },
  { id:'bouleau', n:'Bouleau pubescent', lat:'Betula pubescens', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce et rameaux broutés par l\'élan.',
    hab:'Pionnier, zones humides. Écorce blanche typique.', dng:'—',
    niche:"Pionnier, il colonise en premier les sols nus ou humides que les autres essences mettent des années à atteindre — puis cède peu à peu la place aux arbres plus lents mais plus durables qu'il a lui-même aidé à s'installer." },
  { id:'aulne', n:'Aulne glutineux', lat:'Alnus glutinosa', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines pour tarins et sizerins.',
    hab:'Berges de la Līčupe, sols gorgés d\'eau.', dng:'—',
    niche:"Grâce à une symbiose racinaire qui fixe l'azote de l'air, il prospère dans les sols gorgés d'eau des berges où la plupart des arbres périraient asphyxiés — et enrichit le sol au passage pour les espèces voisines." },
  { id:'epicea', n:'Épicéa commun', lat:'Picea abies', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de cônes pour écureuil, bec-croisé.',
    hab:'Dominant de la forêt boréale. Abri du lynx.', dng:'—',
    niche:"Son feuillage persistant offre un abri toute l'année — y compris en plein hiver — là où les feuillus, dénudés, n'en offrent aucun ; c'est sous ses branches que le lynx trouve souvent refuge." },
  { id:'pin', n:'Pin sylvestre', lat:'Pinus sylvestris', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles = nourriture du grand tétras.',
    hab:'Sols pauvres et sableux. Écorce orangée en haut.', dng:'—',
    niche:"Il s'installe sur les sols pauvres et sableux que la plupart des arbres jugent inhabitables, grâce à des racines capables de puiser l'eau et les nutriments en profondeur là où d'autres essences abandonnent." },
  { id:'tremble', n:'Tremble', lat:'Populus tremula', e:'🌳', cat:'arbres', sub:'Salicacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce très appréciée du castor et du lièvre.',
    hab:'Pionnier, lisières. Feuilles qui tremblent au vent.', dng:'—',
    niche:"Il se propage par ses racines en formant des clones génétiquement identiques, colonisant rapidement les lisières perturbées avant que d'autres essences, plus lentes à s'établir, n'aient eu le temps de s'y installer." },
  { id:'sorbier', n:'Sorbier des oiseleurs', lat:'Sorbus aucuparia', e:'🌳', cat:'arbres', sub:'Rosacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies rouges pour grives, merles, renard.',
    hab:'Lisières, clairières. Baies orangées en automne.', dng:'—',
    niche:"De taille modeste, il occupe l'étage intermédiaire des clairières et lisières que les grands arbres laissent vide, produisant des baies dès l'automne quand peu d'autres ressources fruitières restent disponibles." },
  { id:'tilleul', n:'Tilleul à petites feuilles', lat:'Tilia cordata', e:'🌳', cat:'arbres', sub:'Malvacées', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Fleurs mellifères pour abeilles et bourdons.',
    hab:'Forêts de feuillus, parcs. Arbre symbolique balte.', dng:'—',
    niche:"Il fleurit tardivement, en plein été, quand la plupart des autres arbres ont déjà terminé leur floraison — offrant aux abeilles et bourdons une source de nectar à un moment où la concurrence florale est minimale." },
  { id:'erable', n:'Érable plane', lat:'Acer platanoides', e:'🍁', cat:'arbres', sub:'Sapindacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Samares pour rongeurs et oiseaux.',
    hab:'Forêts mixtes. Feuillage jaune-rouge éclatant en automne.', dng:'—',
    niche:"Ses fruits ailés (samares) lui permettent de coloniser des trouées loin du pied-mère, portées par le vent là où les essences à graines lourdes comme le chêne ne peuvent pas atteindre." },

  { id:'argousier', n:'Argousier faux-nerprun', lat:'Hippophae rhamnoides', e:'🧡', cat:'arbustes', sub:'Éléagnacées', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies acidulées riches en vitamine C, récoltées à l\'automne.',
    hab:'Sols sableux, bords de rivière. Planté sur la propriété.', dng:'—',
    niche:"Fixateur d'azote comme l'aulne, il colonise les sols sableux pauvres des berges où peu d'autres arbustes survivent, et produit ses baies acidulées à l'automne quand la plupart des autres fruits ont déjà disparu." },
  { id:'myrtille', n:'Myrtille commune', lat:'Vaccinium myrtillus', e:'🫐', cat:'arbustes', sub:'Éricacées', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies bleu-noir très recherchées, cueillette d\'été.',
    hab:'Sous-bois acides, pinèdes claires.', dng:'—',
    niche:"Elle exploite les sols acides du sous-bois de pinède, trop pauvres pour la plupart des autres plantes, grâce à une association avec des champignons du sol qui l'aident à en extraire les nutriments." },
  { id:'noisetier', n:'Noisetier commun', lat:'Corylus avellana', e:'🌰', cat:'arbustes', sub:'Bétulacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Noisettes pour écureuil, geai, loir.',
    hab:'Lisières, sous-bois clairs. Chatons dès février.', dng:'—',
    niche:"Il fleurit dès février, bien avant les autres arbustes, à une période où la concurrence pour les pollinisateurs — inexistants à cette saison — ne compte plus : il mise sur le vent plutôt que sur les insectes." },
  { id:'eglantier', n:'Églantier', lat:'Rosa canina', e:'🌹', cat:'arbustes', sub:'Rosacées', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Cynorrhodons riches en vitamine C pour les oiseaux.',
    hab:'Haies, lisières, friches. Fleurs roses en juin.', dng:'⚠️ Tiges épineuses.',
    niche:"Ses tiges épineuses lui permettent de coloniser les haies et friches où le broutage limiterait toute autre plante, et ses fruits (cynorrhodons) persistent jusqu'en hiver, quand la plupart des autres baies ont déjà disparu." },
  { id:'sureau', n:'Sureau noir', lat:'Sambucus nigra', e:'🍇', cat:'arbustes', sub:'Adoxacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies noires pour merles et grives. Fleurs en ombelles blanches.',
    hab:'Haies, lisières, friches humides.', dng:'⚠️ Baies crues légèrement toxiques — à cuire.',
    niche:"Croissance rapide et opportuniste, il colonise les friches humides et haies perturbées avant les essences plus lentes, offrant fleurs puis baies à quelques semaines d'intervalle à deux cortèges d'espèces différents — pollinisateurs, puis oiseaux frugivores." },
  { id:'genevrier', n:'Genévrier commun', lat:'Juniperus communis', e:'🌲', cat:'arbustes', sub:'Cupressacées', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies (cônes) pour grives et sittelles.',
    hab:'Landes, pinèdes claires, sols pauvres.', dng:'—',
    niche:"Il occupe les landes et sols les plus pauvres et secs, là où sa croissance lente — mais sa très grande longévité — lui permet de perdurer sans concurrence, quand des plantes plus rapides mais plus exigeantes ne tiendraient pas." },

  { id:'cepe', n:'Cèpe de Bordeaux', lat:'Boletus edulis', e:'🍄', cat:'champignons', sub:'Bolétales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Symbiose mycorhizienne avec épicéas et pins.',
    hab:'Sous conifères et feuillus. Comestible réputé.', dng:'—',
    niche:"Il vit en symbiose souterraine avec les racines des épicéas et des pins, échangeant sucres contre minéraux — une niche invisible que ni les plantes ni les animaux ne peuvent occuper seuls." },
  { id:'bolet_orange', n:'Bolet orangé', lat:'Leccinum aurantiacum', e:'🍄', cat:'champignons', sub:'Bolétales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec trembles et bouleaux.',
    hab:'Sous trembles. Chapeau orange vif. Comestible.', dng:'—',
    niche:"Associé presque exclusivement aux racines du tremble, il n'apparaît que là où cet arbre pousse — une spécialisation qui limite la concurrence avec les champignons moins exigeants sur leur hôte." },
  { id:'girolle', n:'Girolle', lat:'Cantharellus cibarius', e:'🍄', cat:'champignons', sub:'Cantharellales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec de nombreux arbres.',
    hab:'Forêts moussues. Jaune d\'or, odeur d\'abricot. Comestible.', dng:'—',
    niche:"Contrairement à la plupart des champignons, sa chair résiste bien aux larves d'insectes — elle peut donc rester en place plus longtemps sans être consommée, une niche défensive plutôt qu'une niche d'évitement spatial." },
  { id:'amanite', n:'Amanite tue-mouches', lat:'Amanita muscaria', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec bouleaux et épicéas.',
    hab:'Sous bouleaux. Rouge à points blancs.', dng:'⚠️ Toxique — ne pas consommer.',
    niche:"Sa toxicité la protège de la plupart des animaux qui consomment volontiers d'autres champignons — une stratégie chimique plutôt que spatiale pour échapper à la concurrence de la faune." },
  { id:'russule', n:'Russule charbonnière', lat:'Russula cyanoxantha', e:'🍄', cat:'champignons', sub:'Russulales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhizienne.',
    hab:'Forêts de feuillus. Chapeau violacé-vert. Comestible.', dng:'—',
    niche:"Peu exigeante sur son arbre hôte, elle s'associe à de nombreuses essences de feuillus à la fois — une stratégie généraliste qui lui permet d'apparaître presque partout où le cèpe, plus sélectif, ne pousse pas." },
  { id:'coprin', n:'Coprin chevelu', lat:'Coprinus comatus', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Saprophyte (décompose la matière organique).',
    hab:'Prairies, bords de chemins. Se liquéfie en vieillissant.', dng:'—',
    niche:"Contrairement aux champignons mycorhiziens de la forêt, il décompose directement la matière organique des prairies et bords de chemin — une ressource au sol que les espèces associées aux arbres n'exploitent jamais." },

  { id:'amadouvier', n:'Amadouvier', lat:'Fomes fomentarius', e:'🍄', cat:'champignons', sub:'Polypores', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Parasite puis saprophyte du bois (bouleaux, hêtres affaiblis).',
    hab:'Fixé au tronc, forme de sabot gris. Peut vivre des décennies sur le même arbre.', dng:'—',
    niche:"Contrairement aux champignons du sol, il pousse directement sur l'écorce des bouleaux et hêtres affaiblis, digérant le bois lui-même plutôt que de vivre en symbiose avec les racines — une niche verticale qui ne concurrence en rien les espèces mycorhiziennes." },
  { id:'polypore_bouleau', n:'Polypore du bouleau', lat:'Fomitopsis betulina', e:'🍄', cat:'champignons', sub:'Polypores', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Parasite puis saprophyte, spécifique au bouleau.',
    hab:'Console arrondie beige-brun, exclusivement sur bouleau mort ou mourant.', dng:'—',
    niche:"Strictement inféodé au bouleau, il n'apparaît que là où cet arbre dépérit — une spécialisation aussi étroite que celle du bolet orangé au sol, mais tournée vers le bois plutôt que vers les racines." },
  { id:'chaga', n:'Chaga', lat:'Inonotus obliquus', e:'🍄', cat:'champignons', sub:'Polypores', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:"Parasite du bouleau, se développe des années sous l'écorce.",
    hab:'Masse noire craquelée façon charbon, en excroissance sur le tronc.', dng:'—',
    niche:"Invisible pendant des années sous l'écorce du bouleau vivant avant de faire surface, il exploite un bois encore debout que les décomposeurs du sol ne peuvent atteindre." },
  { id:'polypore_soufre', n:'Polypore soufré', lat:'Laetiporus sulphureus', e:'🍄', cat:'champignons', sub:'Polypores', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Parasite du bois, surtout chênes et feuillus âgés.',
    hab:"Plaques orange vif empilées sur le tronc. Jeune, comestible ; âgé, coriace.", dng:'—',
    niche:"Il s'attaque au cœur du bois des feuillus âgés et affaiblis, une ressource massive et durable que les champignons de sol, liés aux racines fines, ne peuvent exploiter." },
  { id:'polypore_versicolore', n:'Polypore versicolore', lat:'Trametes versicolor', e:'🍄', cat:'champignons', sub:'Polypores', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Saprophyte généraliste du bois mort.',
    hab:'Petites consoles en éventail zonées de couleurs, en rangs serrés sur souches et branches mortes.', dng:'—',
    niche:"Peu exigeant sur l'essence, il colonise en masse la moindre branche morte au sol ou sur pied — un généraliste du bois qui joue, pour les troncs, le rôle que la russule joue pour les racines." },

  { id:'cladonie', n:'Cladonie des rennes', lat:'Cladonia rangiferina', e:'🍃', cat:'lichens', sub:'Lichens', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nourriture hivernale des rennes (nord).',
    hab:'Sols pauvres, pinèdes sèches. Tapis gris clair.', dng:'—',
    niche:"Elle colonise les sols sableux et pauvres où quasiment aucune plante vasculaire ne peut s'installer, formant un tapis qui met des décennies à se reconstituer une fois piétiné." },
  { id:'usnee', n:'Usnée barbue', lat:'Usnea barbata', e:'🍃', cat:'lichens', sub:'Lichens', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Pend des branches. Bio-indicateur d\'air pur.', dng:'—',
    niche:"Suspendue aux branches, elle tire tout ce dont elle a besoin de l'air et de la pluie — sans jamais toucher le sol — mais disparaît dès que l'air se charge en polluants, une niche si exigeante qu'elle sert d'indicateur de qualité de l'air." },
  { id:'sphaigne', n:'Sphaigne', lat:'Sphagnum sp.', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Tourbières, zones humides. Forme la tourbe.', dng:'—',
    niche:"En retenant l'eau comme une éponge et en acidifiant le sol autour d'elle, elle façonne son propre habitat — la tourbière — un milieu si pauvre et gorgé d'eau que presque aucune autre plante ne peut s'y maintenir." },
  { id:'polytric', n:'Polytric commun', lat:'Polytrichum commune', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Sous-bois humides, tourbières. Grande mousse dressée.', dng:'—',
    niche:"Elle occupe la strate la plus basse du sous-bois humide, retenant l'humidité au ras du sol dans un espace trop sombre et trop détrempé pour la plupart des autres plantes." },

  { id:'machaon', n:'Machaon', lat:'Papilio machaon', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur ombellifères, adulte butineur.',
    hab:'Prairies fleuries, lisières. Grand papillon jaune-noir.', dng:'—',
    niche:"Sa chenille ne se développe que sur les ombellifères — une spécialisation qui limite la concurrence avec les autres papillons dont les chenilles exploitent des plantes hôtes différentes." },
  { id:'petit_paon', n:'Paon-du-jour', lat:'Aglais io', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur orties, adulte sur fleurs.',
    hab:'Jardins, lisières. Ocelles bleus en forme d\'yeux.', dng:'—',
    niche:"Sa chenille se nourrit presque exclusivement d'orties, une plante que beaucoup d'herbivores évitent à cause de ses piquants — une ressource urticante devenue une niche presque exclusive pour elle." },
  { id:'lucane', n:'Lucane cerf-volant', lat:'Lucanus cervus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Larve xylophage dans le bois mort de chêne.',
    hab:'Vieux chênes, bois mort. Plus grand coléoptère d\'Europe.', dng:'—',
    niche:"Sa larve se développe pendant plusieurs années dans le bois mort de chêne en décomposition — une ressource si lente à exploiter que très peu d'autres insectes s'y risquent." },
  { id:'carabe', n:'Carabe doré', lat:'Carabus auratus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédateur de limaces, vers, chenilles.',
    hab:'Sol des forêts et jardins. Reflets vert-doré.', dng:'—',
    niche:"Prédateur nocturne au sol, il chasse limaces et chenilles dans la litière — un rôle de régulation que les oiseaux insectivores, actifs le jour, ne peuvent pas assurer." },
  { id:'libellule', n:'Libellule déprimée', lat:'Libellula depressa', e:'🪰', cat:'insectes', sub:'Odonates', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédatrice de moucherons et moustiques.',
    hab:'Bords des lacs et mares. Abdomen large bleuté.', dng:'—',
    niche:"Elle occupe deux niches successives : larve aquatique prédatrice sous l'eau pendant des mois, puis chasseuse aérienne de moucherons au-dessus des mares — un cycle de vie qui lui permet d'exploiter deux milieux qu'aucun autre insecte du domaine ne combine ainsi." },
  { id:'bourdon', n:'Bourdon terrestre', lat:'Bombus terrestris', e:'🐝', cat:'insectes', sub:'Hyménoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nectar et pollen. Pollinisateur majeur.',
    hab:'Prairies, jardins. Niche au sol. Bande jaune.', dng:'Piqûre possible si menacé.',
    niche:"Capable de réchauffer son corps par vibration musculaire, il peut butiner par temps frais ou tôt le matin, quand les abeilles, plus sensibles au froid, restent encore à la ruche." },

  // ═══ POISSONS ═══
  // tailleCm:[a,b] définit les trois paliers pêchés : petit <a, moyen a–b, grand >b
  { id:'brochet', n:'Brochet', lat:'Esox lucius', e:'🐟', cat:'poissons', sub:'Esocidés', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[], tailleCm:[50,80],
    alim:'Carnassier à l\'affût : perches, gardons, petits poissons, grenouilles.',
    hab:'Herbiers et eaux calmes des lacs et de la Līčupe.',
    dng:'Dents acérées — prudence en le décrochant.',
    niche:"Chasseur à l'affût immobile dans les herbiers, il occupe le sommet de la chaîne alimentaire des lacs et de la Līčupe — une stratégie de guet que les poissons plus actifs, comme la perche, n'utilisent pas." },
  { id:'perche', n:'Perche commune', lat:'Perca fluviatilis', e:'🐟', cat:'poissons', sub:'Percidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[], tailleCm:[15,25],
    alim:'Alevins, larves, petits invertébrés aquatiques.',
    hab:'En bancs près des herbiers et des berges, lacs et rivière.',
    dng:'Nageoire dorsale épineuse — attention en la tenant.',
    niche:"Contrairement au brochet à l'affût, elle chasse activement en bancs près des herbiers — les deux prédateurs se partagent ainsi les mêmes eaux avec des techniques de chasse complémentaires plutôt que concurrentes." },
  { id:'sandre', n:'Sandre', lat:'Sander lucioperca', e:'🐟', cat:'poissons', sub:'Percidés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[], tailleCm:[40,65],
    alim:'Carnassier crépusculaire : gardons, perches, petits poissons.',
    hab:'Eaux profondes et troubles des grands lacs.',
    dng:'Dents canines proéminentes — prudence.',
    niche:"Ses yeux adaptés à la faible luminosité lui permettent de chasser efficacement dans les eaux profondes et troubles au crépuscule — un créneau visuel que les autres carnassiers, plus dépendants de la lumière, ne peuvent exploiter aussi bien." },
  { id:'gardon', n:'Gardon', lat:'Rutilus rutilus', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[], tailleCm:[12,20],
    alim:'Algues, larves, petits invertébrés. Omnivore.',
    hab:'En bancs en eaux calmes, lacs et rivière.', dng:'—',
    niche:"Omnivore peu exigeant, il exploite indifféremment algues, larves et petits invertébrés en bancs denses — une stratégie de nombre plutôt que de spécialisation qui le protège partiellement de la prédation." },
  { id:'breme', n:'Brème commune', lat:'Abramis brama', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[], tailleCm:[25,40],
    alim:'Vers, larves, mollusques fouillés dans la vase.',
    hab:'Fonds vaseux des lacs calmes, en bancs.', dng:'—',
    niche:"Elle fouille la vase du fond des lacs calmes à la recherche de vers et de mollusques — une ressource enfouie que les poissons de pleine eau comme le gardon n'exploitent jamais." },
  { id:'tanche', n:'Tanche', lat:'Tinca tinca', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[], tailleCm:[25,40],
    alim:'Vers, larves, végétation aquatique fouillés dans la vase.',
    hab:'Fonds vaseux et herbiers denses, eaux calmes.', dng:'—',
    niche:"Tolérante à de très faibles niveaux d'oxygène, elle occupe les fonds vaseux et les herbiers denses des eaux stagnantes où la plupart des autres poissons ne pourraient pas survivre." },
  { id:'carassin', n:'Carassin commun', lat:'Carassius carassius', e:'🐟', cat:'poissons', sub:'Cyprinidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[], tailleCm:[15,25],
    alim:'Végétation aquatique, larves, détritus.',
    hab:'Eaux calmes et peu profondes, tolère le manque d\'oxygène.', dng:'—',
    niche:"Championne de la tolérance au manque d'oxygène parmi les poissons du domaine, elle survit dans des eaux peu profondes et stagnantes que même la tanche évite en cas de gel prolongé." },

  // ═══ BATRACIENS ═══
  { id:'crapaud', n:'Crapaud commun', lat:'Bufo bufo', e:'🐸', cat:'batraciens', sub:'Bufonidés', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, limaces, cloportes.',
    hab:'Jardins, sous-bois humides. Migre vers les mares au printemps pour se reproduire.',
    dng:'Sa peau sécrète une substance irritante — se laver les mains après manipulation.',
    niche:"Amphibie, il mène une double vie qu'aucun mammifère ou oiseau du domaine ne peut mener : terrestre et nocturne la majeure partie de l'année, chassant dans l'humidité du sous-bois, puis aquatique au printemps pour rejoindre les mares où il se reproduit." },

  // ═══ HUMAINS ═══
  { id:'h_ferdinand', n:'Ferdinand', lat:'Homo sapiens', e:'🧔', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Cueillette, potager, cidre maison. Omnivore opportuniste.',
    hab:'Migrateur saisonnier France ↔ Lettonie. Territoire estival étendu.',
    dng:'Aucun. Peut cependant lancer des chantiers imprévus.' },
  { id:'h_pierre', n:'Pierre', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Co-investisseur. Présence irrégulière.', dng:'Aucun.' },
  { id:'h_elena', n:'Elena', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présente sur la propriété.', dng:'Aucun.' },
  { id:'h_elena2', n:'Elena (2)', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_dasha', n:'Dasha', lat:'Homo sapiens', e:'👧', cat:'humains', sub:'Résidents', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présente sur la propriété.', dng:'Aucun.' },
  { id:'h_yanis', n:'Yanis', lat:'Homo sapiens', e:'👦', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_igor', n:'Igor', lat:'Homo sapiens', e:'👨', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_natacha', n:'Natacha', lat:'Homo sapiens', e:'👩‍🦰', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_natacha2', n:'Natacha (2)', lat:'Homo sapiens', e:'👩‍🦰', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_roman', n:'Roman', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Résidents', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Présent sur la propriété.', dng:'Aucun.' },
  { id:'h_vanya', n:'Vanya', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Travailleurs', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Travaille sur place.', dng:'Aucun.' },
  { id:'h_dasha2', n:'Dasha (2)', lat:'Homo sapiens', e:'👧', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteuse saisonnière. Homonyme — à distinguer de la première.', dng:'Aucun.' },
  { id:'h_loukas', n:'Loukas', lat:'Homo sapiens', e:'👦', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_anna', n:'Anna', lat:'Homo sapiens', e:'👩', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteuse saisonnière.', dng:'Aucun.' },
  { id:'h_cash', n:'Cash', lat:'Homo sapiens', e:'🧑', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Visiteur saisonnier.', dng:'Aucun.' },
  { id:'h_gael', n:'Gaël', lat:'Homo sapiens', e:'🧔', cat:'humains', sub:'Visiteurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Omnivore.', hab:'Aussi aperçu tenant un appareil photo, en train de cataloguer les autres espèces.', dng:'Aucun.' },

  // ═══ ANIMAUX DOMESTIQUES ═══
  { id:'d_sem', n:'Sem', lat:'Canis lupus familiaris', e:'🐕', cat:'domestiques', sub:'Chiens', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Croquettes, restes de table.', hab:'Vit sur la propriété.', dng:'Aucun.' },
  { id:'d_raya', n:'Raya', lat:'Canis lupus familiaris', e:'🐕', cat:'domestiques', sub:'Chiens', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Croquettes, restes de table.', hab:'Vit sur la propriété.', dng:'Aucun.' },
]

// paliers de recensement : nombre d'espèces (le dernier palier = SPECIES.length,
// résolu dynamiquement là où c'est utilisé)
export const TIER_THRESHOLDS = [10, 25, 50, 80, null]

// achievements "tier" (paliers) : progression calculée automatiquement, par
// joueur, à partir du nombre d'espèces qu'il a personnellement observées.
// achievements manuels (manual:true) : aucune donnée ne prouve automatiquement
// qu'ils sont faits (ex. "voir le lynx") — chaque joueur les déclare lui-même
// (auto-déclaratif, voir badgeclaim dans store.js), et c'est cette déclaration
// qui fait progresser sa courbe de 0 à 100%
export const ACHIEVEMENTS = [
  // ── Paliers de recensement ──
  { id:'tier_10',  e:'🌱', n:'Premiers pas',      d:'10 espèces observées',                pts:60,  tier:1 },
  { id:'tier_25',  e:'🌿', n:'Naturaliste',       d:'25 espèces observées',                pts:150, tier:2 },
  { id:'tier_50',  e:'🌳', n:'Connaisseur',       d:'50 espèces observées',                pts:300, tier:3 },
  { id:'tier_80',  e:'🏞️', n:'Encyclopédiste',    d:'80 espèces observées',                pts:500, tier:4 },
  { id:'tier_all', e:'👑', n:'Maître du vivant',  d:'Toutes les espèces du Conservatoire', pts:900, tier:5 },

  // ── Grands prédateurs & espèces difficiles ──
  { id:'lynx',     e:'🐆', n:'Le fantôme',        d:'Voir le lynx de ses propres yeux',    pts:400, manual:true },
  { id:'loup',     e:'🐺', n:'Trace de loup',     d:'Observer un loup ou identifier sa piste', pts:350, manual:true },
  { id:'ours',     e:'🐻', n:'L\'ours',           d:'Observer un ours brun',               pts:600, manual:true },
  { id:'loutre',   e:'🌊', n:'La loutre',         d:'Observer une loutre sur la Līčupe',   pts:280, manual:true },
  { id:'pygargue', e:'🦅', n:'Le pygargue',       d:'Observer un pygargue à queue blanche',pts:220, manual:true },
  { id:'tetras',   e:'🦃', n:'Place de chant',    d:'Assister à la parade du grand tétras',pts:450, manual:true },

  // ── Terrain difficile ──
  { id:'charogne', e:'💀', n:'Charognard',        d:'Trouver une carcasse et identifier l\'espèce', pts:180, manual:true },
  { id:'nid',      e:'🥚', n:'Découvreur de nid', d:'Trouver 3 nids occupés d\'espèces différentes', pts:200, manual:true },
  { id:'terrier',  e:'🕳️', n:'Cartographe souterrain', d:'Localiser 5 terriers ou gîtes actifs', pts:250, manual:true },
  { id:'barrage',  e:'🦫', n:'Ingénieur du castor', d:'Trouver un barrage actif',          pts:190, manual:true },
  { id:'empreinte',e:'🐾', n:'Pisteur',           d:'Identifier 10 empreintes d\'espèces différentes', pts:230, manual:true },
  { id:'cache',    e:'🍖', n:'Reste de repas',    d:'Trouver une proie mise en cache par un prédateur', pts:320, manual:true },

  // ── Individus & suivi ──
  { id:'familier1',e:'⭐', n:'Premier familier',  d:'Reconnaître et nommer un individu',   pts:120, manual:true },
  { id:'clan',     e:'🔖', n:'Le clan',           d:'Suivre 5 familiers différents',       pts:280, manual:true },
  { id:'fidelite', e:'📅', n:'Fidélité',          d:'Revoir le même familier sur 3 saisons', pts:340, manual:true },

  // ── Méthode ──
  { id:'oeil',     e:'👁️', n:'Œil de lynx',       d:'20 espèces vues à l\'œil nu',         pts:260, manual:true },
  { id:'nuit',     e:'🌙', n:'Créature de la nuit', d:'10 espèces en vision nocturne',     pts:240, manual:true },
  { id:'chelem',   e:'🏆', n:'Le grand chelem',   d:'Une espèce de chaque règne, à l\'œil nu', pts:380, manual:true },
]

export function calcPts(sp, playerName) {
  const methods = sp.obs[playerName] || []
  if (!methods.length) return 0
  const best = methods.reduce((b, m) => (METHODS[m]?.mult || 0) > (METHODS[b]?.mult || 0) ? m : b, methods[0])
  const bonuses = sp.bonus[playerName] || []
  return Math.round(
    RARITY[sp.r].p * SIZE_MULT[sp.sz] * (METHODS[best]?.mult || 1) +
    (bonuses.includes('bebe') ? 20 : 0) +
    (bonuses.includes('terrier') ? 30 : 0)
  )
}
export function speciesPts(playerName) {
  return SPECIES.reduce((sum, sp) => sum + calcPts(sp, playerName), 0)
}
export function totalPts(playerName) {
  return speciesPts(playerName) + badgePts(playerName)
}
export function isObserved(sp) {
  return Object.values(sp.obs).some(v => v && v.length)
}
